FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/fitnessapi ./cmd

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/fitnessapi /app/fitnessapi
EXPOSE 8080
CMD ["/app/fitnessapi"]
